name: build
on: [push]

env:
  ENGINE: pdflatex
  FILE: cv

jobs:
  build-main:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    steps:
      - name: Install Node.js
        run: |
          apt-get update
          apt-get install -y curl
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: report
      - name: Compile PDF
        run: |
          latexmk -pdf -pdflatex="${{ env.ENGINE }} --shell-escape %O %S" ${{ env.FILE }}
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        with:
          name: report-pdf
          path: ${{ env.FILE }}.pdf

  deploy:
    needs: [build-main]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: report
      - name: Download PDF
        uses: actions/download-artifact@v3
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        with:
          name: report-pdf
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "Creating release for tag ${{ github.ref_name }}"
          echo "PDF available at ./${{ env.FILE }}.pdf"

